### PR TITLE
cask_package allows several packages to be installed

### PR DESCRIPTION
**Pull request by ifosch**

### CODE REVIEW

**Comment by ninjabong** [comment]
Cool!  I'll give this and your updated brew_package a whirl later before I merge, at quick glance it looks fine though.

also: nice limecat avatar! 8)

**Comment by ifosch** [comment]
Glad you liked both! I've been using osxc for the last few days (reinstalled my Mac on Sunday) and I made some improvements I'm PRing to you now. Hope you like all the rest also. Let me know if there's anything I could do to improve them.

**Comment by ifosch** [comment]
Of course, if in any of those PRs I made code changes that could be avoided by any other way, please, let me know, maybe I just would help improving doc.

**Comment by ninjabong** [comment]
@rricard is the real lead, I'm just someone like yourself you who really enjoyed osxc and found ansible easy enough to work with, and some places that could be improved.

I like how both these keep existing playbooks working as well as supporting a list of items for a cleaner playbook moving forward, something that has [come up before](https://github.com/osxc/xc-common/issues/6).

**Comment by rricard** [comment]
Nah, I have to thank @ninjabong that were more available than me those last times on the project !

**Pull request merged**
