### PR TITLE
fixed homebrew_cask_opts - missing close quote

### PR DESCRIPTION
**Pull request by rjacoby**
homebrew_cask role was failing; could not modify .zshenv due to missing close quote after the 'line' snippet.

### CODE REVIEW

**Comment by ninjabong** [comment]
whoops, that one is my bad - good catch!

**Comment by casidiablo** [comment]
This is still in master :scream:

**Comment by ninjabong** [comment]
yeah, have to wait for rricard to merge into master

**Comment by rricard** [comment]
Yup sorry ! Had a busy schedule !

**Pull request merged**
